image: ubuntu/cosmic
sources:
  - https://github.com/termux/x11-packages
packages:
  - build-essential
  - asciidoc
  - asciidoctor
  - autoconf
  - automake
  - bison
  - curl
  - ed
  - flex
  - g++-multilib
  - gawk
  - gettext
  - git
  - gnome-common
  - gtk-3-examples
  - gtk-doc-tools
  - gperf
  - help2man
  - intltool
  - libexpat1-dev
  - libgdk-pixbuf2.0-dev
  - libgmp-dev
  - libgtk-3-bin
  - libglib2.0-dev
  - libisl-dev
  - libjpeg-dev
  - libmpc-dev
  - libmpfr-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libssl-dev
  - libtool-bin
  - lzip
  - m4
  - openjdk-8-jdk-headless
  - pax-utils
  - pkg-config
  - python-pip
  - python3.7
  - python3-docutils
  - python3-pip
  - python3-setuptools
  - python3-sphinx
  - ruby
  - scons
  - texinfo
  - unzip
  - xfonts-utils
  - xmlto
  - zip
  - zlib1g-dev
tasks:
  - prepare: |
      sudo mkdir -p /data/data/com.termux/files/usr
      sudo chown -R $(id -u):$(id -u) /data
  - initialize-package-tree: |
      cd ./x11-packages
      cp -a ./packages/* ./termux-packages/packages/
  - install-android-sdk: |
      cd ./x11-packages/termux-packages
      bash ./scripts/setup-android-sdk.sh > /dev/null
  - process-last-commit: |
      cd ./x11-packages/termux-packages
      bash ../scripts/ci-process-last-commit.sh
