container:
  image: xeffyr/termux-advanced-builder:latest
  cpu: 4
  memory: 8

##
##  Perform basic check for errors in build.sh package scripts.
##  If error found, exit with error code to stop build.
##
task:
  name: Lint packages

  timeout_in: 5m

  lint_script: |
    bash ./scripts/lint-packages.sh

##
##  Determine changes in the last push, find modified packages and
##  build them for aarch64/arm/i686/x86_64 architectures for both
##  Android API 21 and 24.
##
##  Built packages are accessible from Cirrus CI web interface.
##
task:
  name: Build packages

  timeout_in: 120m

  depends_on:
    - Lint packages

  environment:
    TERMUX_MAKE_PROCESSES: 4
    matrix:
      - TERMUX_ARCH: aarch64
        LEGACY_ANDROID: false
      - TERMUX_ARCH: aarch64
        LEGACY_ANDROID: true
      - TERMUX_ARCH: arm
        LEGACY_ANDROID: false
      - TERMUX_ARCH: arm
        LEGACY_ANDROID: true
      - TERMUX_ARCH: i686
        LEGACY_ANDROID: false
      - TERMUX_ARCH: i686
        LEGACY_ANDROID: true
      - TERMUX_ARCH: x86_64
        LEGACY_ANDROID: false
      - TERMUX_ARCH: x86_64
        LEGACY_ANDROID: true

  build_script: |
    bash ./scripts/cirrus-ci_dispatcher.sh

  output_artifacts:
    path: "./termux-packages/debs/*.deb"

##
##  When doing release build (branch 'master'), upload built packages
##  to APT repository on Bintray.
##
task:
  only_if: $CIRRUS_BRANCH == 'master'

  name: Upload packages to Bintray

  timeout_in: 60m

  depends_on:
    - Build packages

  environment:
    BINTRAY_USERNAME: ENCRYPTED[90abba51ac0c50d868f2d78ac4d48ed0fe8ecb79d53f15697afd261c440c7999cbe910696a65221668b3826cff3c756f]
    BINTRAY_API_KEY: ENCRYPTED[0329a0c1d74d51a02f47e1ab5a079a017959bafa8b241cbc6a0404217a8719ed7ded99837db9c1846cb17309657dfc8d]
    matrix:
      - LEGACY_ANDROID: false
      - LEGACY_ANDROID: true

  upload_script: |
    bash ./scripts/cirrus-ci_dispatcher.sh --upload
